export const metadata = {
  title: {
    absolute: "",
    default: "Next JS Practice",
    template: "%s | Next JS",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
